[[34m2024-09-22T23:39:39.451+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:40:39.511+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:41:39.572+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:42:39.637+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:43:39.697+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:44:39.763+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:45:39.829+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:46:39.893+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:47:39.958+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:48:40.015+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:49:40.068+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:50:40.135+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:51:40.199+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:52:40.258+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:53:40.317+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:54:40.382+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:55:40.449+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:56:40.505+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:57:40.565+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:58:40.626+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-22T23:59:40.686+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-23T00:00:40.755+0300[0m] {[34mtriggerer_job_runner.py:[0m474} INFO[0m - 0 triggers currently running[0m
[[34m2024-09-23T00:01:14.694+0300[0m] {[34mtriggerer_job_runner.py:[0m334} ERROR[0m - Exception when executing TriggererJobRunner._run_trigger_loop[0m
Traceback (most recent call last):
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 733, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: job.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/airflow/jobs/triggerer_job_runner.py", line 332, in _execute
    self._run_trigger_loop()
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/airflow/jobs/triggerer_job_runner.py", line 360, in _run_trigger_loop
    perform_heartbeat(self.job, heartbeat_callback=self.heartbeat_callback, only_if_necessary=True)
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/airflow/jobs/job.py", line 350, in perform_heartbeat
    job.heartbeat(heartbeat_callback=heartbeat_callback, session=session)
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/airflow/jobs/job.py", line 211, in heartbeat
    session.commit()
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3386, in flush
    self._flush(objects)
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3525, in _flush
    with util.safe_reraise():
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3486, in _flush
    flush_context.execute()
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "/home/zaurall/projects/pmldl-mlops/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 733, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: job.id
[SQL: INSERT INTO job (id, dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ((2, None, <JobState.RUNNING: 'running'>, 'TriggererJob', '2024-09-21 20:23:33.124651', None, '2024-09-22 21:01:09.091135', None, 'DESKTOP-QAR5BLG.', 'zaurall'), (2, None, <JobState.RUNNING: 'running'>, 'TriggererJob', '2024-09-21 20:23:33.124651', None, '2024-09-22 21:01:09.091135', None, 'DESKTOP-QAR5BLG.', 'zaurall'))]
(Background on this error at: https://sqlalche.me/e/14/gkpj)[0m
[[34m2024-09-23T00:01:14.694+0300[0m] {[34mtriggerer_job_runner.py:[0m337} INFO[0m - Waiting for triggers to clean up[0m
[[34m2024-09-23T00:01:14.795+0300[0m] {[34mtriggerer_job_runner.py:[0m343} INFO[0m - Exited trigger loop[0m
